### PR TITLE
UI overhaul, issue #2

### PR DESCRIPTION
**Pull request by kartikarora**
Please don't create a merge commit, use the command line method instead. The commit history of forked repositories becomes difficult to maintain otherwise.

### CODE REVIEW

**Comment by Pritom14** [comment]
Thanks for the PR :) , you could also check some other issues in this repository

**Comment by kartikarora** [comment]
You made a merge commit :neutral_face:

**Comment by Pritom14** [comment]
I am really sorry, but I am new to this. Could you please explain me what to and what not to do?

**Comment by kartikarora** [comment]
When you get a PR, github gives you an option to merge it manually, then it shows you a couple of git commands to do that. Please use that.

What happened right now is that your merge added a new commit, so if someone had already made a commit and then pulls your new commit here, the commit history will be broken.

If you merge it manually, there is no new commit created, hence so scope of commit history being broken.

Anyway, I'll manage it for now!

**Comment by Pritom14** [comment]
Okay, thanks for the info. Do you want me to revert the PR, so that I can merge it manually?

**Comment by kartikarora** [comment]
No no, its fine for now!

**Comment by kartikarora** [comment]
This is how it looks now, in case you're unable to run it right now!
device-2017-10-11-133013

**Comment by Pritom14** [comment]
Thanks

**Pull request merged**
